site_name: DOCUMENTAÇÃO - LAMFO
repo_url: https://github.com/th-org/LAMFO

nav: 
  - Home: index.md
  - Atas:
    - Ata modelo: atas/modelo.md
theme: 
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette: 
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
icon:
  repo: fontawesome/brands/git-alt

include: 
  - README.md